language: r
r: 
  - 3.5.1
sudo: required
before_install:
- sudo mkdir -p /usr/lib/R/library
- echo 'R_LIBS=/usr/lib/R/library:/usr/lib/R/site-library/' > ~/.Renviron
- sudo chmod 2777 /usr/lib/R/library
- sudo add-apt-repository -y ppa:opencpu/jq
- sudo apt-get update
- sudo apt-get install libproj-dev libgdal-dev libv8-3.14-dev libprotobuf-dev protobuf-compiler libjq-dev 
install:
- R -e "0" --args --bootstrap-packrat
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/packrat/src"
  - "$TRAVIS_BUILD_DIR/packrat/lib"
  packages: true
script:
- Rscript -e 'download.file("https://drive.google.com/open?id=1uBfl0_vrHbb-cNwCcpGFtt6WKyBr70qy",destfile = "~/data/")'
- nohup R --slave --no-restore -e 'shiny::runApp(port = 3000)' &
- R -f test.R
addons:
  sauce_connect:
    username: "$SAUCE_USERNAME"
    access_key: "$SAUCE_SECRET_KEY"
deploy:
  provider: script
  script: 
  - R -f deploy.R
  skip_cleanup: true
  on: 
    branch: master
    repo: dfe-analytical-services/lgbt-survey-2017